### ISSUE TITLE
Navigating the sections is difficult using Firefox on Android

### ISSUE THREAD

**Issue by CuttlefishXXX** [SICPDistilled/website#6]
When attempting to navigate by dragging, I am able to drag the navigation to scroll it but sometimes it jumps back to the top without me being able to go to the section I wanted.

As an immediate aid to make navigation simpler, I recommend adding "previous" and "next" links at the bottom of each page.

**Comment by thattommyhall** [comment]
@CuttlefishXXX is this OK for you in FF?

**Comment by CuttlefishXXX** [comment]
@thattommyhall: It's still a bit jumpy but it's an improvement. I maintain that "previous" and "next" navigation buttons at the bottom of each page would be helpful to avoid annoyance with the jumpyness.

**Comment by CuttlefishXXX** [comment]
In particular, the jumping I observe now occurs in the navigation menu when the main text has been scrolled to the bottom. (As opposed to earlier where the navigation would jump no matter what scroll position the main text was at.)

**Comment by thattommyhall** [comment]
I'll raise a spearate issue for prev/next as I do intend to do it. Having it on middleman as of yday is a useful simplification and I am glad this change makes it a bit better for you
